version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/abdul-hamid-achik/tinyvault

linters:
  enable:
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - hugeParam

    gosec:
      excludes:
        - G104
      config:
        global:
          audit: true

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    unparam:
      check-exported: false

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      # Exclude test files from various linters
      - path: _test\.go
        linters:
          - dupl
          - gocyclo
          - gocognit
          - gosec
          - errcheck
          - govet
          - goconst
          - errorlint
          - revive
          - staticcheck
          - gocritic

      # Exclude generated database code
      - path: internal/database/db/
        linters:
          - all

      # Allow longer functions in cmd
      - path: cmd/
        linters:
          - gocyclo
          - gocognit

      # Duplicate code in services is acceptable (Create/Update/Upsert patterns)
      - path: internal/services/
        linters:
          - dupl

      # Crypto package name collision is intentional
      - path: internal/crypto/
        linters:
          - revive
        text: "var-naming: avoid package names"

      # Viper errors are intentionally ignored in CLI code
      - linters:
          - errcheck
        text: "viper\\."

      # JSON encode errors in HTTP handlers (client disconnected)
      - linters:
          - errcheck
        text: "json\\.NewEncoder\\(w\\)\\.Encode"

      # Template render errors are handled by the framework
      - linters:
          - errcheck
        text: "component\\.Render"

      # Context value type assertions are intentionally unchecked
      - linters:
          - errcheck
        text: "ctx\\.Value"

      # Transaction rollback errors in panic handlers
      - linters:
          - errcheck
        text: "tx\\.Rollback"

      # JSON unmarshal of optional metadata
      - linters:
          - errcheck
        text: "json\\.Unmarshal\\(log\\.Metadata"

      # Signal errors during shutdown
      - linters:
          - errcheck
        text: "Process\\.Signal"

      # os.Stdin.Stat for detecting pipe input
      - linters:
          - errcheck
        text: "os\\.Stdin\\.Stat"

      # High cognitive complexity is acceptable for certain handlers
      - path: internal/handlers/
        linters:
          - gocognit

      - path: internal/middleware/
        linters:
          - gocognit

      # Shadow variables in handlers are acceptable
      - path: internal/handlers/
        linters:
          - govet
        text: "shadow"

      - path: internal/services/
        linters:
          - govet
        text: "shadow"

      # Disable gocritic for range value copies (acceptable for our data sizes)
      - linters:
          - gocritic
        text: "rangeValCopy"

      # Import shadowing is acceptable when parameter names are clear
      - linters:
          - gocritic
        text: "importShadow"

      # goconst suggestions are optional - disable globally
      - path: ".*"
        linters:
          - goconst

      # goprintffuncname is optional - disable globally
      - path: ".*"
        linters:
          - goprintffuncname

      # godot comment endings are optional - disable globally
      - path: ".*"
        linters:
          - godot

      # gosec warnings that are handled appropriately
      - linters:
          - gosec
        text: "G404"

      # gosec integer overflow is acceptable for config values
      - linters:
          - gosec
        text: "G115"

      # revive unused-parameter for HTTP handlers
      - path: internal/handlers/
        linters:
          - revive
        text: "unused-parameter"

      # gocritic suggestions that are stylistic
      - linters:
          - gocritic
        text: "unnamedResult"

      - linters:
          - gocritic
        text: "equalFold"

      - linters:
          - gocritic
        text: "httpNoBody"

      - linters:
          - gocritic
        text: "exitAfterDefer"

      # wastedassign - disable globally
      - path: ".*"
        linters:
          - wastedassign

      # JSON encode in health handlers
      - path: internal/handlers/health\.go
        linters:
          - errcheck
        text: "Encode"

      # JSON encode in API handlers
      - path: internal/handlers/api\.go
        linters:
          - errcheck
        text: "Encode"

      # JSON encode in middleware
      - path: internal/middleware/
        linters:
          - errcheck
        text: "Encode"

      # Context value type assertions are intentional
      - path: internal/middleware/auth\.go
        linters:
          - errcheck
        source: "ctx\\.Value"

      # JSON unmarshal of optional metadata
      - path: internal/services/audit_service\.go
        linters:
          - errcheck
        text: "json\\.Unmarshal"
