version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/abdul-hamid-achik/tinyvault

linters:
  enable:
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - gocognit
    - gocritic
    - gocyclo
    #- goprintffuncname  # disabled: our Success/Error/Warning/Info names are intentional
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - tparallel
    - unconvert
    - unparam
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - hugeParam

    gosec:
      excludes:
        - G104
      config:
        global:
          audit: true

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    unparam:
      check-exported: false

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      # Exclude test files from various linters
      - path: _test\.go
        linters:
          - dupl
          - gocyclo
          - gocognit
          - gosec
          - errcheck
          - govet
          - errorlint
          - revive
          - staticcheck
          - gocritic

      # Allow longer functions in cmd
      - path: cmd/
        linters:
          - gocyclo
          - gocognit

      # Crypto package name collision is intentional
      - path: internal/crypto/
        linters:
          - revive
        text: "var-naming: avoid package names"

      # Viper errors are intentionally ignored in CLI code
      - linters:
          - errcheck
        text: "viper\\."

      # Signal errors during shutdown
      - linters:
          - errcheck
        text: "Process\\.Signal"

      # os.Stdin.Stat for detecting pipe input
      - linters:
          - errcheck
        text: "os\\.Stdin\\.Stat"

      # Disable gocritic for range value copies
      - linters:
          - gocritic
        text: "rangeValCopy"

      # Import shadowing is acceptable
      - linters:
          - gocritic
        text: "importShadow"

      # gocritic stylistic suggestions
      - linters:
          - gocritic
        text: "unnamedResult"

      - linters:
          - gocritic
        text: "exitAfterDefer"

      # gosec integer overflow is acceptable for config values
      - linters:
          - gosec
        text: "G115"
