version: 2

project_name: tinyvault

before:
  hooks:
    - go mod tidy

builds:
  - id: tvault
    main: ./cmd/tvault
    binary: tvault
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: tvault
    builds:
      - tvault
    name_template: "tvault_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: tvault
    ids:
      - tvault
    repository:
      owner: abdul-hamid-achik
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/abdul-hamid-achik/tinyvault"
    description: "Dead simple secrets management CLI and MCP server"
    license: "MIT"
    install: |
      bin.install "tvault"
    test: |
      system "#{bin}/tvault", "--version"
    skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"

nfpms:
  - id: packages
    package_name: tvault
    vendor: TinyVault
    homepage: https://github.com/abdul-hamid-achik/tinyvault
    maintainer: Abdul Hamid Achik <abdul.achik@gmail.com>
    description: "Dead simple secrets management CLI and MCP server"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

release:
  github:
    owner: abdul-hamid-achik
    name: tinyvault
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
