// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByUser = `-- name: CountAuditLogsByUser :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1
`

func (q *Queries) CountAuditLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByUserActionSince = `-- name: CountAuditLogsByUserActionSince :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1 AND action = $2 AND created_at > $3
`

type CountAuditLogsByUserActionSinceParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	Action    string      `db:"action" json:"action"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) CountAuditLogsByUserActionSince(ctx context.Context, arg CountAuditLogsByUserActionSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByUserActionSince, arg.UserID, arg.Action, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByUserSince = `-- name: CountAuditLogsByUserSince :one
SELECT COUNT(*) FROM audit_logs WHERE user_id = $1 AND created_at > $2
`

type CountAuditLogsByUserSinceParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) CountAuditLogsByUserSince(ctx context.Context, arg CountAuditLogsByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at
`

type CreateAuditLogParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	Action       string      `db:"action" json:"action"`
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	ResourceName *string     `db:"resource_name" json:"resource_name"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_logs
WHERE created_at < $1
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldAuditLogs, createdAt)
	return err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at FROM audit_logs WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id uuid.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at FROM audit_logs
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActionParams struct {
	Action string `db:"action" json:"action"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByResource = `-- name: ListAuditLogsByResource :many
SELECT id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at FROM audit_logs
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByResourceParams struct {
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditLogs = `-- name: ListRecentAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, resource_name, ip_address, user_agent, metadata, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentAuditLogsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRecentAuditLogs(ctx context.Context, arg ListRecentAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
