// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
)

const countActiveAPITokens = `-- name: CountActiveAPITokens :one
SELECT COUNT(*) FROM api_tokens
WHERE revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
`

// Count all non-revoked and non-expired API tokens
func (q *Queries) CountActiveAPITokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPITokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT COUNT(*) FROM sessions WHERE expires_at > NOW()
`

// Count all non-expired sessions
func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProjects = `-- name: CountAllProjects :one
SELECT COUNT(*) FROM projects WHERE deleted_at IS NULL
`

// Count all non-deleted projects
func (q *Queries) CountAllProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllSecrets = `-- name: CountAllSecrets :one
SELECT COUNT(*) FROM secrets s
INNER JOIN projects p ON s.project_id = p.id
WHERE p.deleted_at IS NULL
`

// Count all secrets for non-deleted projects
func (q *Queries) CountAllSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}
