// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Name       string             `db:"name" json:"name"`
	TokenHash  []byte             `db:"token_hash" json:"token_hash"`
	Scopes     []string           `db:"scopes" json:"scopes"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type AuditLog struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	Action       string      `db:"action" json:"action"`
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	ResourceName *string     `db:"resource_name" json:"resource_name"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	Metadata     []byte      `db:"metadata" json:"metadata"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

type LoginAttempt struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Email     string      `db:"email" json:"email"`
	IpAddress *netip.Addr `db:"ip_address" json:"ip_address"`
	Success   bool        `db:"success" json:"success"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

type Project struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	OwnerID      uuid.UUID          `db:"owner_id" json:"owner_id"`
	Name         string             `db:"name" json:"name"`
	Description  *string            `db:"description" json:"description"`
	EncryptedDek []byte             `db:"encrypted_dek" json:"encrypted_dek"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time          `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Secret struct {
	ID             uuid.UUID `db:"id" json:"id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue []byte    `db:"encrypted_value" json:"encrypted_value"`
	Version        int32     `db:"version" json:"version"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TokenHash    []byte      `db:"token_hash" json:"token_hash"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	LastActiveAt time.Time   `db:"last_active_at" json:"last_active_at"`
}

type User struct {
	ID            uuid.UUID `db:"id" json:"id"`
	GithubID      *int64    `db:"github_id" json:"github_id"`
	Email         string    `db:"email" json:"email"`
	Username      string    `db:"username" json:"username"`
	Name          *string   `db:"name" json:"name"`
	AvatarUrl     *string   `db:"avatar_url" json:"avatar_url"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
	PasswordHash  *string   `db:"password_hash" json:"password_hash"`
	AuthProvider  string    `db:"auth_provider" json:"auth_provider"`
	EmailVerified bool      `db:"email_verified" json:"email_verified"`
}
