// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countProjectsByOwner = `-- name: CountProjectsByOwner :one
SELECT COUNT(*) FROM projects
WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name, description, encrypted_dek)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OwnerID      uuid.UUID `db:"owner_id" json:"owner_id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	EncryptedDek []byte    `db:"encrypted_dek" json:"encrypted_dek"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.EncryptedDek,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByIDWithOwner = `-- name: GetProjectByIDWithOwner :one
SELECT id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetProjectByIDWithOwnerParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	OwnerID uuid.UUID `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetProjectByIDWithOwner(ctx context.Context, arg GetProjectByIDWithOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDWithOwner, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at FROM projects
WHERE owner_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetProjectByNameParams struct {
	OwnerID uuid.UUID `db:"owner_id" json:"owner_id"`
	Name    string    `db:"name" json:"name"`
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.OwnerID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectDEK = `-- name: GetProjectDEK :one
SELECT encrypted_dek FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectDEK(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectDEK, id)
	var encrypted_dek []byte
	err := row.Scan(&encrypted_dek)
	return encrypted_dek, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at FROM projects
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByOwnerParams struct {
	OwnerID uuid.UUID `db:"owner_id" json:"owner_id"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, arg ListProjectsByOwnerParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.EncryptedDek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, owner_id, name, description, encrypted_dek, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectDEK = `-- name: UpdateProjectDEK :exec
UPDATE projects
SET encrypted_dek = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProjectDEKParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	EncryptedDek []byte    `db:"encrypted_dek" json:"encrypted_dek"`
}

func (q *Queries) UpdateProjectDEK(ctx context.Context, arg UpdateProjectDEKParams) error {
	_, err := q.db.Exec(ctx, updateProjectDEK, arg.ID, arg.EncryptedDek)
	return err
}
