// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Check if email exists for a given auth provider
	CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error)
	CleanupOldLoginAttempts(ctx context.Context, createdAt time.Time) error
	CountActiveAPITokensByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountAuditLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountProjectsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error)
	CountSecretsByProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Creates a user from GitHub OAuth (github_id required)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Creates a user from email/password registration
	CreateUserFromEmail(ctx context.Context, arg CreateUserFromEmailParams) (User, error)
	DeleteAPIToken(ctx context.Context, id uuid.UUID) error
	DeleteAllSecretsByProject(ctx context.Context, projectID uuid.UUID) error
	DeleteAllSessionsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldAuditLogs(ctx context.Context, createdAt time.Time) error
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) error
	DeleteSecretByID(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByHash(ctx context.Context, tokenHash []byte) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ExtendSession(ctx context.Context, arg ExtendSessionParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error)
	GetAPITokenWithUser(ctx context.Context, tokenHash []byte) (GetAPITokenWithUserRow, error)
	GetAuditLogByID(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetLastSuccessfulLogin(ctx context.Context, email string) (LoginAttempt, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByIDWithOwner(ctx context.Context, arg GetProjectByIDWithOwnerParams) (Project, error)
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error)
	GetProjectDEK(ctx context.Context, id uuid.UUID) ([]byte, error)
	GetSecretByID(ctx context.Context, id uuid.UUID) (Secret, error)
	GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error)
	GetSecretWithValue(ctx context.Context, arg GetSecretWithValueParams) (Secret, error)
	GetSessionByHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionWithUser(ctx context.Context, tokenHash []byte) (GetSessionWithUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Gets user by email for authentication (email auth provider only)
	GetUserByEmailForAuth(ctx context.Context, email string) (User, error)
	GetUserByGitHubID(ctx context.Context, githubID *int64) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HardDeleteProject(ctx context.Context, id uuid.UUID) error
	ListAPITokensByUser(ctx context.Context, arg ListAPITokensByUserParams) ([]ApiToken, error)
	ListActiveAPITokensByUser(ctx context.Context, userID uuid.UUID) ([]ApiToken, error)
	ListActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListProjectsByOwner(ctx context.Context, arg ListProjectsByOwnerParams) ([]Project, error)
	ListRecentAuditLogs(ctx context.Context, arg ListRecentAuditLogsParams) ([]AuditLog, error)
	ListSecretKeysByProject(ctx context.Context, projectID uuid.UUID) ([]string, error)
	ListSecretsByProject(ctx context.Context, arg ListSecretsByProjectParams) ([]ListSecretsByProjectRow, error)
	ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error
	RevokeAllAPITokensByUser(ctx context.Context, userID uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectDEK(ctx context.Context, arg UpdateProjectDEKParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
	UpdateSessionActivity(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) (Secret, error)
	// Upsert for GitHub users (uses github_id as conflict key)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
