// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSecretsByProject = `-- name: CountSecretsByProject :one
SELECT COUNT(*) FROM secrets WHERE project_id = $1
`

func (q *Queries) CountSecretsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (project_id, key, encrypted_value)
VALUES ($1, $2, $3)
RETURNING id, project_id, key, encrypted_value, version, created_at, updated_at
`

type CreateSecretParams struct {
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue []byte    `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret, arg.ProjectID, arg.Key, arg.EncryptedValue)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllSecretsByProject = `-- name: DeleteAllSecretsByProject :exec
DELETE FROM secrets WHERE project_id = $1
`

func (q *Queries) DeleteAllSecretsByProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSecretsByProject, projectID)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets
WHERE project_id = $1 AND key = $2
`

type DeleteSecretParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	Key       string    `db:"key" json:"key"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.Exec(ctx, deleteSecret, arg.ProjectID, arg.Key)
	return err
}

const deleteSecretByID = `-- name: DeleteSecretByID :exec
DELETE FROM secrets WHERE id = $1
`

func (q *Queries) DeleteSecretByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecretByID, id)
	return err
}

const getSecretByID = `-- name: GetSecretByID :one
SELECT id, project_id, key, encrypted_value, version, created_at, updated_at FROM secrets WHERE id = $1
`

func (q *Queries) GetSecretByID(ctx context.Context, id uuid.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByID, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, project_id, key, encrypted_value, version, created_at, updated_at FROM secrets
WHERE project_id = $1 AND key = $2
`

type GetSecretByKeyParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	Key       string    `db:"key" json:"key"`
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, arg.ProjectID, arg.Key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretWithValue = `-- name: GetSecretWithValue :one
SELECT id, project_id, key, encrypted_value, version, created_at, updated_at FROM secrets
WHERE project_id = $1 AND key = $2
`

type GetSecretWithValueParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	Key       string    `db:"key" json:"key"`
}

func (q *Queries) GetSecretWithValue(ctx context.Context, arg GetSecretWithValueParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretWithValue, arg.ProjectID, arg.Key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretKeysByProject = `-- name: ListSecretKeysByProject :many
SELECT key FROM secrets
WHERE project_id = $1
ORDER BY key ASC
`

func (q *Queries) ListSecretKeysByProject(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSecretKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByProject = `-- name: ListSecretsByProject :many
SELECT id, project_id, key, version, created_at, updated_at
FROM secrets
WHERE project_id = $1
ORDER BY key ASC
LIMIT $2 OFFSET $3
`

type ListSecretsByProjectParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

type ListSecretsByProjectRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	Key       string    `db:"key" json:"key"`
	Version   int32     `db:"version" json:"version"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSecretsByProject(ctx context.Context, arg ListSecretsByProjectParams) ([]ListSecretsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listSecretsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsByProjectRow{}
	for rows.Next() {
		var i ListSecretsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET encrypted_value = $3
WHERE project_id = $1 AND key = $2
RETURNING id, project_id, key, encrypted_value, version, created_at, updated_at
`

type UpdateSecretParams struct {
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue []byte    `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret, arg.ProjectID, arg.Key, arg.EncryptedValue)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSecret = `-- name: UpsertSecret :one
INSERT INTO secrets (project_id, key, encrypted_value)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, key) DO UPDATE
SET encrypted_value = EXCLUDED.encrypted_value
RETURNING id, project_id, key, encrypted_value, version, created_at, updated_at
`

type UpsertSecretParams struct {
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue []byte    `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, upsertSecret, arg.ProjectID, arg.Key, arg.EncryptedValue)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
