// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT COUNT(*) FROM sessions
WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) CountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, ip_address, user_agent, expires_at, created_at, last_active_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	TokenHash []byte      `db:"token_hash" json:"token_hash"`
	IpAddress *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent *string     `db:"user_agent" json:"user_agent"`
	ExpiresAt time.Time   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteAllSessionsByUser = `-- name: DeleteAllSessionsByUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByUser, userID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions
SET expires_at = $2, last_active_at = NOW()
WHERE id = $1
`

type ExtendSessionParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, created_at, last_active_at FROM sessions
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, created_at, last_active_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.id, s.user_id, s.token_hash, s.ip_address, s.user_agent, s.expires_at, s.created_at, s.last_active_at,
    u.id AS user_id,
    u.github_id,
    u.email,
    u.username,
    u.name,
    u.avatar_url
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token_hash = $1 AND s.expires_at > NOW()
`

type GetSessionWithUserRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TokenHash    []byte      `db:"token_hash" json:"token_hash"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	LastActiveAt time.Time   `db:"last_active_at" json:"last_active_at"`
	UserID_2     uuid.UUID   `db:"user_id_2" json:"user_id_2"`
	GithubID     *int64      `db:"github_id" json:"github_id"`
	Email        string      `db:"email" json:"email"`
	Username     string      `db:"username" json:"username"`
	Name         *string     `db:"name" json:"name"`
	AvatarUrl    *string     `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.UserID_2,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, created_at, last_active_at FROM sessions
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, created_at, last_active_at FROM sessions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionsByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions
SET last_active_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, id)
	return err
}
