// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND auth_provider = $2) AS exists
`

type CheckEmailExistsParams struct {
	Email        string `db:"email" json:"email"`
	AuthProvider string `db:"auth_provider" json:"auth_provider"`
}

// Check if email exists for a given auth provider
func (q *Queries) CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, arg.Email, arg.AuthProvider)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (github_id, email, username, name, avatar_url, auth_provider, email_verified)
VALUES ($1, $2, $3, $4, $5, 'github', true)
RETURNING id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified
`

type CreateUserParams struct {
	GithubID  *int64  `db:"github_id" json:"github_id"`
	Email     string  `db:"email" json:"email"`
	Username  string  `db:"username" json:"username"`
	Name      *string `db:"name" json:"name"`
	AvatarUrl *string `db:"avatar_url" json:"avatar_url"`
}

// Creates a user from GitHub OAuth (github_id required)
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GithubID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const createUserFromEmail = `-- name: CreateUserFromEmail :one
INSERT INTO users (email, username, password_hash, auth_provider, email_verified)
VALUES ($1, $2, $3, 'email', false)
RETURNING id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified
`

type CreateUserFromEmailParams struct {
	Email        string  `db:"email" json:"email"`
	Username     string  `db:"username" json:"username"`
	PasswordHash *string `db:"password_hash" json:"password_hash"`
}

// Creates a user from email/password registration
func (q *Queries) CreateUserFromEmail(ctx context.Context, arg CreateUserFromEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFromEmail, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified FROM users WHERE email = $1 AND auth_provider = 'email'
`

// Gets user by email for authentication (email auth provider only)
func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.Email,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.AuthProvider,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, username = $3, name = $4, avatar_url = $5
WHERE id = $1
RETURNING id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified
`

type UpdateUserParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Email     string    `db:"email" json:"email"`
	Username  string    `db:"username" json:"username"`
	Name      *string   `db:"name" json:"name"`
	AvatarUrl *string   `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash *string   `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_id, email, username, name, avatar_url, auth_provider, email_verified)
VALUES ($1, $2, $3, $4, $5, 'github', true)
ON CONFLICT (github_id) DO UPDATE
SET email = EXCLUDED.email,
    username = EXCLUDED.username,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url
WHERE users.github_id IS NOT NULL
RETURNING id, github_id, email, username, name, avatar_url, created_at, updated_at, password_hash, auth_provider, email_verified
`

type UpsertUserParams struct {
	GithubID  *int64  `db:"github_id" json:"github_id"`
	Email     string  `db:"email" json:"email"`
	Username  string  `db:"username" json:"username"`
	Name      *string `db:"name" json:"name"`
	AvatarUrl *string `db:"avatar_url" json:"avatar_url"`
}

// Upsert for GitHub users (uses github_id as conflict key)
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.EmailVerified,
	)
	return i, err
}
